security:
    providers:
        users_in_memory: { memory: null }
        app_user_provider:
            entity:
                class: App\Entity\User
                property: nickname
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            lazy: true
            provider: users_in_memory
            guard:
                authenticators:
                    - App\Security\TeamChapoAuthenticator
            logout:
                path: logout
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
    encoders:
        App\Entity\User:
            algorithm: 'argon2i'
            memory_cost: 1024
            time_cost: 3
